package notDeafult;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Load extends javax.swing.JFrame {

    /**
     * Creates new form Load
     */
    public Load() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namecombo = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loadg = new javax.swing.JButton();
        main = new javax.swing.JButton();
        deletesg = new javax.swing.JButton();
        deleteall = new javax.swing.JButton();
        addpswd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        namecombo.setBackground(new java.awt.Color(102, 102, 102));
        namecombo.setForeground(new java.awt.Color(0, 255, 0));
        namecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namecomboActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font( "minecraftia" , Font.BOLD, 12 ));
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Please select your name:");

        jLabel2.setFont(new Font( "minecraftia" , Font.BOLD, 12 ));
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Please select your saved game:");

        jLabel3.setFont(new Font( "minecraftia" , Font.BOLD, 25 ));
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Load Game");
        jLabel3.setToolTipText("");

        loadg.setBackground(new java.awt.Color(0, 0, 0));
        loadg.setFont(new Font( "minecraftia" , Font.PLAIN, 15 ));
        loadg.setForeground(new java.awt.Color(0, 255, 0));
        loadg.setText("Load saved game");
        loadg.setPreferredSize(new java.awt.Dimension(125, 23));
        loadg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadgActionPerformed(evt);
            }
        });

        main.setBackground(new java.awt.Color(0, 0, 0));
        main.setFont(new Font( "minecraftia" , Font.PLAIN, 15 ));
        main.setForeground(new java.awt.Color(0, 255, 0));
        main.setText("Main Menu");
        main.setPreferredSize(new java.awt.Dimension(125, 23));
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        deletesg.setBackground(new java.awt.Color(0, 0, 0));
        deletesg.setFont(new Font( "minecraftia" , Font.PLAIN, 15 ));
        deletesg.setForeground(new java.awt.Color(0, 255, 0));
        deletesg.setText("Delete saved game");
        deletesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesgActionPerformed(evt);
            }
        });

        deleteall.setBackground(new java.awt.Color(0, 0, 0));
        deleteall.setFont(new Font( "minecraftia" , Font.PLAIN, 15 ));
        deleteall.setForeground(new java.awt.Color(0, 255, 0));
        deleteall.setText("Delete all saved games");
        deleteall.setMaximumSize(new java.awt.Dimension(125, 23));
        deleteall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteallActionPerformed(evt);
            }
        });

        addpswd.setBackground(new java.awt.Color(0, 0, 0));
        addpswd.setFont(new Font( "minecraftia" , Font.PLAIN, 15 ));
        addpswd.setForeground(new java.awt.Color(0, 255, 0));
        addpswd.setText("Add Password");
        addpswd.setPreferredSize(new java.awt.Dimension(125, 23));
        addpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpswdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deletesg, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(loadg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteall, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(namecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addpswd, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addpswd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loadg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletesg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteall, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void namecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namecomboActionPerformed
        //Get Name combo box
        jComboBox2.removeAllItems();        //Starts wih a new list every time a combo box is called

        JComboBox jComboBox1 = (JComboBox) evt.getSource();
        String selection = (String) jComboBox1.getSelectedItem(); //Get the name
        SaveLoadGame slg = new SaveLoadGame();

        for (int i = 0; i < slg.getSubdir("saves/" + selection).length; i++) { //loop for the length of the subdirectory
            jComboBox2.addItem(slg.getSubdir("saves/" + selection)[i]);
        }
    }//GEN-LAST:event_namecomboActionPerformed

    private void loadgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadgActionPerformed
        String name = namecombo.getSelectedItem().toString(); //Get Name
        String save = jComboBox2.getSelectedItem().toString();//Get save
        SaveLoadGame slg = new SaveLoadGame();
        try {

            slg.loadGame(name, save);//Send a parameters to he Load method
        } catch (IOException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FontFormatException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();

    }//GEN-LAST:event_loadgActionPerformed

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        // TODO add your handling code here:
        MainMenu mn = new MainMenu();
        mn.setVisible(true);
        dispose(); //Open the Main Menu
    }//GEN-LAST:event_mainActionPerformed

    private void deletesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesgActionPerformed

        //Similarly to the Load method, the delete does simply deletes he file
        String name = namecombo.getSelectedItem().toString();
        String save = jComboBox2.getSelectedItem().toString();
        SaveLoadGame slg = new SaveLoadGame();
        try {
            slg.deleteGame("saves/" + name + "/" + save); //Send path needing deletion
            JOptionPane.showMessageDialog(null, "Sucess '" + save + "' deleted"); //Print the path has been deleted
        } catch (IOException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletesgActionPerformed

    private void deleteallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteallActionPerformed
        SaveLoadGame slg = new SaveLoadGame();
        try {
            slg.deleteGame("saves");
            //Deletes the Entire saves directory, this can be done because when saving a game the save method must always first
            //call a MakeDir directory
            JOptionPane.showMessageDialog(null, "All Saves deleted");
            MainMenu mn = new MainMenu();
            mn.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteallActionPerformed

    private void addpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpswdActionPerformed

        String name = namecombo.getSelectedItem().toString();
        String save = jComboBox2.getSelectedItem().toString();

        SaveLoadGame slg = new SaveLoadGame();
        try {
            JOptionPane.showMessageDialog(null, slg.addPassword(name, save));
            //As usual the name and save are sent as parameters to have a password added to it
        } catch (IOException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addpswdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpswd;
    private javax.swing.JButton deleteall;
    private javax.swing.JButton deletesg;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadg;
    private javax.swing.JButton main;
    public javax.swing.JComboBox namecombo;
    // End of variables declaration//GEN-END:variables
}
